export enum EAllocationRequestStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  SUBMITTED = "SUBMITTED",
  ALLOCATED = "ALLOCATED",
  DUPLICATE = "DUPLICATE",
}