export enum ELeaveType {
  ANNUAL = "ANNUAL",
  SICK = "SICK",
  STUDY = "STUDY",
  BEREAVEMENT = "BEREAVEMENT",
  FAMILY_RESPONSIBLITY = "FAMILY_RESPONSIBLITY",
  MATERNITY = "MATERNITY",
  PATERNITY = "PATERNITY",
  UNPAID = "UNPAID"
}

export enum ELeaveRequestStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED"
}